name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go test -v ./...
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go build cmd/*.go
      - uses: actions/upload-artifact@v3
        with:
          name: containerd-shim-rund-v1
          path: containerd-shim-rund-v1
